import { VehicleConfig, VehicleId } from '../../types/game';

export const VEHICLE_CONFIGS: Record<VehicleId, VehicleConfig> = {
  city_car: {
    id: 'city_car',
    name: 'Northbridge Compact',
    category: 'Passenger Car',
    description: 'A nimble, balanced hatchback perfect for navigating central city streets, parking in tight bays, and passenger errands.',
    price: 0,
    topSpeed: 140,
    acceleration: 68,
    braking: 75,
    handling: 82,
    passengerCapacity: 3,
    cargoCapacity: 2,
    unlockedByDefault: true,
    color: '#3B82F6',
    availableColors: ['#3B82F6', '#EF4444', '#10B981', '#F59E0B', '#64748B', '#1E293B', '#F8FAFC'],
    wheelStyle: 'sport',
    bodyDimensions: {
      width: 1.8,
      height: 1.45,
      length: 4.2,
      wheelbase: 2.6,
    },
  },
  taxi_sedan: {
    id: 'taxi_sedan',
    name: 'Metro Cab Sedan',
    category: 'Taxi Service',
    description: 'Equipped with an illuminated roof sign and reinforced chassis. Ideal for fast passenger pickups and timed city rides.',
    price: 500,
    topSpeed: 155,
    acceleration: 74,
    braking: 78,
    handling: 80,
    passengerCapacity: 4,
    cargoCapacity: 2,
    unlockedByDefault: false,
    color: '#F59E0B',
    availableColors: ['#F59E0B', '#EAB308', '#F97316'],
    wheelStyle: 'classic',
    bodyDimensions: {
      width: 1.85,
      height: 1.5,
      length: 4.6,
      wheelbase: 2.75,
    },
  },
  delivery_van: {
    id: 'delivery_van',
    name: 'Courier High-Roof Van',
    category: 'Logistics Van',
    description: 'High cargo capacity with sturdy suspension. Perfect for delivering packages, food crates, and supplies to shops across town.',
    price: 750,
    topSpeed: 125,
    acceleration: 58,
    braking: 70,
    handling: 65,
    passengerCapacity: 1,
    cargoCapacity: 12,
    unlockedByDefault: true,
    color: '#06B6D4',
    availableColors: ['#06B6D4', '#3B82F6', '#64748B', '#F8FAFC', '#E2E8F0', '#10B981'],
    wheelStyle: 'heavy',
    bodyDimensions: {
      width: 2.0,
      height: 2.2,
      length: 5.2,
      wheelbase: 3.2,
    },
  },
  city_bus: {
    id: 'city_bus',
    name: 'Northbridge City Transit Bus',
    category: 'Public Transit',
    description: 'Full-size municipal passenger bus with pneumatic doors and electronic ticket dispenser. Run scheduled routes and serve commuters.',
    price: 1200,
    topSpeed: 95,
    acceleration: 42,
    braking: 60,
    handling: 45,
    passengerCapacity: 32,
    cargoCapacity: 0,
    unlockedByDefault: true,
    color: '#2563EB',
    availableColors: ['#2563EB', '#16A34A', '#DC2626', '#D97706'],
    wheelStyle: 'heavy',
    bodyDimensions: {
      width: 2.4,
      height: 2.9,
      length: 9.6,
      wheelbase: 5.8,
    },
  },
  box_truck: {
    id: 'box_truck',
    name: 'Freight Hauler Box Truck',
    category: 'Heavy Freight',
    description: 'Heavy dual-axle commercial transport built for heavy industrial deliveries, warehouse loading docks, and high-value cargo.',
    price: 1600,
    topSpeed: 105,
    acceleration: 46,
    braking: 55,
    handling: 50,
    passengerCapacity: 1,
    cargoCapacity: 24,
    unlockedByDefault: false,
    color: '#DC2626',
    availableColors: ['#DC2626', '#EA580C', '#475569', '#1E293B', '#F8FAFC'],
    wheelStyle: 'heavy',
    bodyDimensions: {
      width: 2.45,
      height: 3.1,
      length: 8.4,
      wheelbase: 4.8,
    },
  },
  motorbike: {
    id: 'motorbike',
    name: 'Apex Street Courier Bike',
    category: 'Motorcycle',
    description: 'Ultra-agile 650cc street bike with realistic lean dynamics. Weaves through narrow alleys and heavy traffic for urgent courier dispatches.',
    price: 900,
    topSpeed: 170,
    acceleration: 92,
    braking: 85,
    handling: 95,
    passengerCapacity: 0,
    cargoCapacity: 3,
    unlockedByDefault: false,
    color: '#84CC16',
    availableColors: ['#84CC16', '#EF4444', '#06B6D4', '#F59E0B', '#1E293B'],
    wheelStyle: 'sport',
    bodyDimensions: {
      width: 0.8,
      height: 1.2,
      length: 2.1,
      wheelbase: 1.4,
    },
  },
  camper_van: {
    id: 'camper_van',
    name: 'Wanderer Scenic Camper',
    category: 'Recreational Vehicle',
    description: 'Equipped with a retro pop-up canvas roof, panoramic touring windows, cozy travel cabin, and rooftop luggage rack. The ultimate vehicle for peaceful long-distance road trips.',
    price: 850,
    topSpeed: 120,
    acceleration: 60,
    braking: 68,
    handling: 72,
    passengerCapacity: 4,
    cargoCapacity: 10,
    unlockedByDefault: true,
    color: '#F97316',
    availableColors: ['#F97316', '#14B8A6', '#F59E0B', '#3B82F6', '#64748B', '#E2E8F0'],
    wheelStyle: 'classic',
    bodyDimensions: {
      width: 2.05,
      height: 2.25,
      length: 5.4,
      wheelbase: 3.3,
    },
  },
};
