import { WeatherConfig, WeatherId } from '../../types/game';

export const WEATHER_CONFIGS: Record<WeatherId, WeatherConfig> = {
  // 1. Clear Morning (Cool sunlight, long shadows, crisp distance)
  clear_morning: {
    id: 'clear_morning',
    name: 'Clear Morning',
    description: 'Crisp cool morning sun, long soft shadows, crystal clear horizon and fresh tarmac grip.',
    skyColor: 0x7eb3e8,
    horizonColor: 0xd4e9fa,
    sunColor: 0xfff5e6,
    sunIntensity: 2.1,
    ambientColor: 0x93bfe3,
    ambientIntensity: 0.82,
    fogColor: 0xcbe2f5,
    fogNear: 220,
    fogFar: 750,
    gripMultiplier: 1.0,
    isNight: false,
    hasPrecipitation: false,
    particleCount: 0,
    windSpeed: 2,
    roadWetness: 0.05,
  },

  // 2. Sunny Afternoon (Bright warm light, stronger contrast, optimal visibility)
  sunny_afternoon: {
    id: 'sunny_afternoon',
    name: 'Sunny Afternoon',
    description: 'Warm brilliant sunlight, high contrast, vibrant foliage and maximum tire grip.',
    skyColor: 0x4a9be6,
    horizonColor: 0xb4d8fb,
    sunColor: 0xfffaed,
    sunIntensity: 2.5,
    ambientColor: 0x86b3dc,
    ambientIntensity: 0.85,
    fogColor: 0xaecfed,
    fogNear: 260,
    fogFar: 850,
    gripMultiplier: 1.0,
    isNight: false,
    hasPrecipitation: false,
    particleCount: 0,
    windSpeed: 3,
    roadWetness: 0.0,
  },

  // 3. Sunset (Orange sky, long shadows, warm glowing windows)
  sunset: {
    id: 'sunset',
    name: 'Golden Sunset',
    description: 'Breathtaking golden-hour twilight, amber horizons, long dramatic vehicle shadows and warm glass reflections.',
    skyColor: 0x9a3412, // deep warm twilight
    horizonColor: 0xfb923c, // bright amber orange
    sunColor: 0xfed7aa,
    sunIntensity: 1.8,
    ambientColor: 0xc2410c,
    ambientIntensity: 0.75,
    fogColor: 0xf97316,
    fogNear: 150,
    fogFar: 550,
    gripMultiplier: 1.0,
    isNight: false,
    hasPrecipitation: false,
    particleCount: 0,
    windSpeed: 2,
    roadWetness: 0.05,
  },

  // 4. Rainy Day (Darker sky, wet road sheen, mist, droplets)
  rainy_day: {
    id: 'rainy_day',
    name: 'Rainy Day',
    description: 'Overcast slate skies, rhythmic rain droplets, reflective wet sheen on asphalt, and reduced cornering traction.',
    skyColor: 0x334155,
    horizonColor: 0x475569,
    sunColor: 0x94a3b8,
    sunIntensity: 0.9,
    ambientColor: 0x475569,
    ambientIntensity: 0.7,
    fogColor: 0x475569,
    fogNear: 80,
    fogFar: 360,
    gripMultiplier: 0.74,
    isNight: false,
    hasPrecipitation: true,
    precipitationType: 'rain',
    particleCount: 1800,
    windSpeed: 8,
    roadWetness: 0.9,
  },

  // 5. Snowy Day (Blue-gray sky, snow banks, flakes, pale terrain)
  snowy_day: {
    id: 'snowy_day',
    name: 'Snowy Day',
    description: 'Quiet falling snow, frosty asphalt shoulders, low tire traction requiring smooth throttle and earlier braking.',
    skyColor: 0x64748b,
    horizonColor: 0xcfdce8,
    sunColor: 0xf1f5f9,
    sunIntensity: 1.2,
    ambientColor: 0x94a3b8,
    ambientIntensity: 0.85,
    fogColor: 0xb8cddf,
    fogNear: 70,
    fogFar: 340,
    gripMultiplier: 0.52,
    isNight: false,
    hasPrecipitation: true,
    precipitationType: 'snow',
    particleCount: 2000,
    windSpeed: 4,
    roadWetness: 0.45,
  },

  // 6. Clear Night (Dark sky, stars, headlights, roadside lamps)
  clear_night: {
    id: 'clear_night',
    name: 'Clear Night',
    description: 'Deep starlit night sky, bright headlight cones cutting through the dark, and serene quiet highway cruising.',
    skyColor: 0x030712,
    horizonColor: 0x0b1329,
    sunColor: 0x1e293b, // soft moonlight
    sunIntensity: 0.35,
    ambientColor: 0x0f172a,
    ambientIntensity: 0.4,
    fogColor: 0x0b1329,
    fogNear: 120,
    fogFar: 440,
    gripMultiplier: 1.0,
    isNight: true,
    hasPrecipitation: false,
    particleCount: 0,
    windSpeed: 2,
    roadWetness: 0.08,
  },

  // 7. Storm Night (Rain, wind, flashes, strong haze)
  storm_night: {
    id: 'storm_night',
    name: 'Storm Night',
    description: 'Turbulent thunderstorm, whipping rain, rolling thunder, lightning flashes, and challenging high-atmosphere road grip.',
    skyColor: 0x020617,
    horizonColor: 0x090f1f,
    sunColor: 0x1e293b,
    sunIntensity: 0.2,
    ambientColor: 0x090d16,
    ambientIntensity: 0.35,
    fogColor: 0x080e1a,
    fogNear: 50,
    fogFar: 280,
    gripMultiplier: 0.62,
    isNight: true,
    hasPrecipitation: true,
    precipitationType: 'rain',
    particleCount: 2600,
    windSpeed: 16,
    roadWetness: 0.98,
  },

  // Backward-compatible aliases
  sunny: {
    id: 'sunny',
    name: 'Sunny Afternoon',
    description: 'Warm brilliant sunlight, high contrast, vibrant foliage and maximum tire grip.',
    skyColor: 0x4a9be6,
    horizonColor: 0xb4d8fb,
    sunColor: 0xfffaed,
    sunIntensity: 2.5,
    ambientColor: 0x86b3dc,
    ambientIntensity: 0.85,
    fogColor: 0xaecfed,
    fogNear: 260,
    fogFar: 850,
    gripMultiplier: 1.0,
    isNight: false,
    hasPrecipitation: false,
    particleCount: 0,
    windSpeed: 3,
    roadWetness: 0.0,
  },
  rainy: {
    id: 'rainy',
    name: 'Rainy Day',
    description: 'Overcast slate skies, rhythmic rain droplets, reflective wet sheen on asphalt, and reduced cornering traction.',
    skyColor: 0x334155,
    horizonColor: 0x475569,
    sunColor: 0x94a3b8,
    sunIntensity: 0.9,
    ambientColor: 0x475569,
    ambientIntensity: 0.7,
    fogColor: 0x475569,
    fogNear: 80,
    fogFar: 360,
    gripMultiplier: 0.74,
    isNight: false,
    hasPrecipitation: true,
    precipitationType: 'rain',
    particleCount: 1800,
    windSpeed: 8,
    roadWetness: 0.9,
  },
  snowy: {
    id: 'snowy',
    name: 'Snowy Day',
    description: 'Quiet falling snow, frosty asphalt shoulders, low tire traction requiring smooth throttle and earlier braking.',
    skyColor: 0x64748b,
    horizonColor: 0xcfdce8,
    sunColor: 0xf1f5f9,
    sunIntensity: 1.2,
    ambientColor: 0x94a3b8,
    ambientIntensity: 0.85,
    fogColor: 0xb8cddf,
    fogNear: 70,
    fogFar: 340,
    gripMultiplier: 0.52,
    isNight: false,
    hasPrecipitation: true,
    precipitationType: 'snow',
    particleCount: 2000,
    windSpeed: 4,
    roadWetness: 0.45,
  },
};
